<?php

namespace Database\Seeders;

use App\Models\Dasha;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DashaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $data = [
            [
                'planet' => 'SUYRA',
                'your_personalized_planetary_insights' => 'During this phase, the Sun’s powerful influence will illuminate your path toward success and recognition. You are likely to experience significant growth in your career, particularly in leadership roles or positions of authority. The Sun enhances your confidence, allowing you to shine in public life, whether that’s in business, politics, or creative fields. Opportunities to work with the government or high-ranking officials may emerge, and promotions or public acknowledgment of your efforts are likely. However, this period also tests your ego, pushing you to refine and balance it. You may feel a strong desire to achieve personal success and recognition, sometimes prioritizing personal pleasures over family obligations. Creativity and artistic pursuits will flourish, and you may discover or enhance hidden talents. Be mindful of relationships, as your increased confidence and charisma may attract attention, but avoid indulgences that could complicate your personal life. Ultimately, this is a time for cultivating your leadership abilities, focusing on self-expression, and establishing your identity in the world. Embrace opportunities for growth, but ensure that you balance personal ambition with humility, as ego can either elevate or hinder your progress depending on how it’s managed during this phase.'
            ],
            [
                'planet' => 'CHANDRA',
                'your_personalized_planetary_insights' => 'The Moon brings a period of emotional balance and contentment, drawing your focus toward home, family, and inner peace. You will feel a deep connection to your loved ones, especially maternal figures, and may spend more time nurturing your domestic life. This phase encourages a sense of harmony in your surroundings, allowing you to create a beautiful and peaceful environment where you feel secure and happy. Expect increased creativity, as the Moon stimulates your imagination, inspiring you to work on home projects or artistic endeavors. You may even consider starting a home-based business or exploring ventures that allow you to work in a comfortable, familiar setting. The Moon also amplifies your appreciation for nature, leading you to seek solace in natural landscapes like gardens or near water bodies. Materially, this period may bring gains in property, vehicles, or other assets, enhancing your comfort and security. Challenges may arise, but your calm and composed nature will allow you to handle them gracefully, without losing your emotional equilibrium. This phase is marked by contentment, emotional maturity, and a sense of fulfillment that comes from nurturing both yourself and those around you, creating a peaceful and stable foundation for your life.'
            ],
            [
                'planet' => 'GURU',
                'your_personalized_planetary_insights' => 'Jupiter’s expansive energy brings great fortune, wisdom, and growth into your life. During this period, you’ll experience an increase in wealth, knowledge, and social status. For students, this is an ideal time to excel academically, with the possibility of gaining admission to prestigious institutions or receiving scholarships. If you’re in business or leadership roles, expect to see significant growth in your endeavors. Jupiter’s influence also extends to spiritual development, making this an excellent time to explore esoteric subjects like astrology, spirituality, or the occult. You may gain profound insights into the nature of life, allowing you to predict events or understand hidden patterns. Happiness from your family will be prominent, with marriages, births, or other auspicious events likely to occur. Friendships with influential, prosperous individuals will further boost your social standing, and you may even receive recognition or honors from the government. This is a time for growth not just in material wealth but also in wisdom and personal fulfillment. Jupiter encourages you to expand your horizons, seek knowledge, and cultivate relationships with people who enrich your life both materially and spiritually, bringing a sense of fulfillment and purpose to everything you do.'
            ],
            [
                'planet' => 'RAHU',
                'your_personalized_planetary_insights' => 'Rahu’s influence can bring unexpected opportunities and challenges, especially in terms of material wealth, travel, and relationships. During this phase, you might experience sudden gains in wealth or property, often through unexpected means such as inheritance, foreign ventures, or speculative investments. This period may also introduce foreign travel or even permanent relocation, presenting opportunities to explore new cultures or business markets. Success during Rahu’s phase depends heavily on your perseverance and ability to navigate obstacles, as rewards will come after significant effort. While financial gains are possible, you’ll need to stay focused and work hard to achieve your goals. Rahu’s energy is intense, and it can also bring sudden shifts in your personal life, including marriage or deep connections with influential people. However, there may be hurdles along the way, and you’ll need to maintain a strong sense of self-discipline to overcome them. Rahu also amplifies ambition, making you more determined to succeed. This period could open doors to foreign opportunities or partnerships, but success requires caution and careful decision-making. Overall, Rahu encourages you to embrace change, take calculated risks, and remain persistent in your pursuit of success, ensuring that your hard work ultimately pays off.'
            ],
            [
                'planet' => 'BUDH',
                'your_personalized_planetary_insights' => 'Mercury enhances your intellectual abilities, communication skills, and creativity during this period, making it an ideal time for learning, teaching, and expanding your knowledge. You may feel a strong urge to pursue new skills or further your education, whether through formal studies or self-taught methods. This phase brings a focus on communication, and you’ll likely find yourself excelling in writing, speaking, or negotiating. Professions that require clear communication, such as journalism, law, media, or marketing, will benefit you greatly. Mercury also governs technology, so you might be drawn to careers or projects related to the internet, software development, or digital media. You’ll feel mentally sharp, eager to solve problems, and motivated to think outside the box. Business ventures, especially those involving communication, networking, or trade, will flourish under Mercury’s influence. However, this period may also bring challenges in the form of obstacles or debts, which you’ll need to overcome with persistence and strategic thinking. Mercury encourages you to focus on health, suggesting that maintaining a balanced diet and regular exercise will be essential for your overall well-being. Relationships will benefit from clear and open communication, helping you resolve conflicts and strengthen connections.'
            ],
            [
                'planet' => 'SHUKRA',
                'your_personalized_planetary_insights' => 'Venus brings a time of luxury, comfort, and artistic success, making this period one of enjoyment and material abundance. You’ll likely experience gains through luxurious items like jewelry, vehicles, or high-value assets, enhancing your sense of prosperity and well-being. Venus rules over beauty and the arts, so if you work in creative fields like music, design, fashion, or entertainment, this is a particularly auspicious time for you. Your creative projects will thrive, and you may find new opportunities to showcase your talents to a wider audience. This period also encourages harmony in your personal life, with happiness and prosperity surrounding your family and relationships. Expect a heightened sense of emotional fulfillment, as Venus strengthens your connections with loved ones. Financially, Venus not only brings wealth in the form of money but also through investments, stocks, or inheritances. Your career will benefit from Venus’s influence, particularly if it involves aesthetics, design, or artistic expression. You’ll feel more inclined to indulge in life’s pleasures, but it’s important to balance enjoyment with responsibility. Venus encourages you to embrace the finer things in life while maintaining a sense of harmony and gratitude for the abundance that surrounds you.'
            ],
            [
                'planet' => 'KETU',
                'your_personalized_planetary_insights' => 'Ketu’s influence urges you to focus on spiritual growth and detachment from material concerns during this phase. This is a time for introspection, as Ketu encourages you to seek a deeper understanding of life’s purpose and to connect with higher spiritual truths. You may feel drawn to studying sacred texts, meditation, or spiritual practices that help you cultivate inner peace and wisdom. If you have a mentor or spiritual guide, this is an ideal period to learn from them and deepen your spiritual journey. Ketu also enhances your intuitive and psychic abilities, making it a powerful time to explore healing arts, natural remedies, and holistic wellness. Unexpected events may occur during this phase, but they often serve as catalysts for personal growth and liberation. Ketu’s energy is transformative, helping you shed old patterns and attachments that no longer serve your higher purpose. While material gains may not be the focus of this period, the spiritual insights and inner peace you gain will be invaluable. Ketu encourages you to prioritize your spiritual path, embrace detachment from worldly desires, and cultivate wisdom that will benefit you in the long term, guiding you toward liberation and self-realization.'
            ],
            [
                'planet' => 'SHANI',
                'your_personalized_planetary_insights' => 'Saturn’s energy brings structure, discipline, and long-term rewards, making this phase one of hard work, persistence, and ultimate success. Saturn often tests your patience and resilience, pushing you to work diligently toward your goals. However, the rewards for your efforts will be substantial, including wealth, social status, and recognition. Professionally, you may experience significant growth, particularly if you’re willing to take on more responsibility and commit to long-term projects. Saturn’s influence also extends to your personal life, where you’ll develop stronger relationships with family and friends, particularly those built on mutual respect and loyalty. Financial gains are likely, especially through investments, property, or business ventures that require careful planning and patience. This period also emphasizes personal growth through challenges, as Saturn teaches you valuable lessons in perseverance and self-discipline. While the road may seem tough at times, the rewards are worth the effort. Saturn encourages you to build a solid foundation for the future, both materially and emotionally. By embracing Saturn’s lessons of patience, hard work, and responsibility, you’ll emerge from this phase stronger, wiser, and with a clear sense of purpose, ready to achieve lasting success.'
            ],
            [
                'planet' => 'MANGAL',
                'your_personalized_planetary_insights' => 'Mars fills you with energy, motivation, and a desire to take action, making this a period of intense focus and determination. You’ll feel driven to pursue your goals with vigor, whether in business, personal projects, or fitness endeavors. Mars encourages you to take bold steps, complete unfinished tasks, and tackle new challenges head-on. This phase is ideal for making progress in areas that require physical or mental strength, such as sports, entrepreneurship, or leadership roles. However, Mars also brings fluctuations in wealth, so be prepared for both gains and losses during this time. It’s important to stay grounded and avoid impulsive decisions, particularly in financial matters. Physically, you’ll feel more active and may take up new fitness routines or outdoor activities that challenge your endurance and strength. Mars can also stir up competitive or aggressive tendencies, so it’s crucial to channel your energy constructively and avoid conflicts. This is a time for standing up for what you believe in and fighting for your goals, but it’s equally important to remain mindful of how you approach challenges. Mars teaches you that persistence and strategic action are key to overcoming obstacles and achieving lasting success.'
            ]
        ];
                Dasha::insert($data);
    }
}
